using Content.Shared.Chat;
using Content.Shared.CCVar;
using Robust.Shared.Utility;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;
using System.Linq;

namespace Content.Client.UserInterface.Systems.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChannelFilterPopup : Popup
{
    // order in which the available channel filters show up when available
    private static readonly ChatChannel[] ChannelFilterOrder =
    {
        ChatChannel.Local,
        ChatChannel.Whisper,
        ChatChannel.Subtle,
        ChatChannel.SubtleOOC,
        ChatChannel.Emotes,
        ChatChannel.Radio,
        ChatChannel.Notifications,
        ChatChannel.Telepathic, //Nyano - Summary: adds telepathic chat to where it belongs in order in the chat.
        ChatChannel.LOOC,
        ChatChannel.OOC,
        ChatChannel.Dead,
        ChatChannel.Admin,
        ChatChannel.AdminAlert,
        ChatChannel.AdminChat,
        ChatChannel.Server
    };

    private readonly Dictionary<ChatChannel, ChannelFilterCheckbox> _filterStates = new();

    private RadioFilterWindow? _radioFilterWindow;

    public event Action<ChatChannel, bool>? OnChannelFilter;
    public event Action<string>? OnNewHighlights;
    public event Action? OnRadioFilterChanged;
    public event Action? OnFilterBulkUpdated; // HardLight: Added "Toggle All" button to channel filter popup

    public ChannelFilterPopup()
    {
        RobustXamlLoader.Load(this);

        HighlightButton.OnPressed += HighlightsEntered;
        RadioFilterButton.OnPressed += OnRadioFilterButtonPressed;
        AllChannelsCheckbox.OnToggled += OnAllChannelCheckboxToggled; // HardLight: Added "Toggle All" button to channel filter popup
        // Add a placeholder text to the highlights TextEdit.
        HighlightEdit.Placeholder = new Rope.Leaf(Loc.GetString("hud-chatbox-highlights-placeholder"));

        // Load highlights if any were saved.
        var cfg = IoCManager.Resolve<IConfigurationManager>();
        string highlights = cfg.GetCVar(CCVars.ChatHighlights);

        if (!string.IsNullOrEmpty(highlights))
        {
            UpdateHighlights(highlights);
        }
    }

    public bool IsActive(ChatChannel channel)
    {
        return _filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed;
    }

    public void SetActive(ChatChannel channel, bool isActive)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox) && checkbox.Pressed != isActive)
        {
            checkbox.Pressed = isActive;
            OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        }
    }

    public ChatChannel GetActive()
    {
        ChatChannel active = 0;

        foreach (var (key, value) in _filterStates)
        {
            if (value.IsHidden || !value.Pressed)
            {
                continue;
            }

            active |= key;
        }

        return active;
    }

    public void SetChannels(ChatChannel channels)
    {
        foreach (var channel in ChannelFilterOrder)
        {
            if (!_filterStates.TryGetValue(channel, out var checkbox))
            {
                checkbox = new ChannelFilterCheckbox(channel);
                _filterStates.Add(channel, checkbox);
                checkbox.OnPressed += CheckboxPressed;
                checkbox.Pressed = true;
            }

            if ((channels & channel) == 0)
            {
                if (checkbox.Parent == ChannelFiltersVBox) // HardLight: FilterVBox -> ChannelFiltersVBox, Added "Toggle All" button to channel filter popup
                    ChannelFiltersVBox.RemoveChild(checkbox); // HardLight: FilterVBox -> ChannelFiltersVBox, Added "Toggle All" button to channel filter popup
            }
            else if (checkbox.IsHidden)
            {
                ChannelFiltersVBox.AddChild(checkbox); // HardLight: FilterVBox -> ChannelFiltersVBox, Added "Toggle All" button to channel filter popup
            }
        }
        UpdateAllChannelCheckboxState(); // HardLight: Added "Toggle All" button to channel filter popup
    }

    public void UpdateHighlights(string highlights)
    {
        HighlightEdit.TextRope = new Rope.Leaf(highlights);
    }

    private void CheckboxPressed(ButtonEventArgs args)
    {
        var checkbox = (ChannelFilterCheckbox) args.Button;
        OnChannelFilter?.Invoke(checkbox.Channel, checkbox.Pressed);
        UpdateAllChannelCheckboxState(); // HardLight: Added "Toggle All" button to channel filter popup
    }

    private void HighlightsEntered(ButtonEventArgs _args)
    {
        OnNewHighlights?.Invoke(Rope.Collapse(HighlightEdit.TextRope));
    }

    private void OnRadioFilterButtonPressed(ButtonEventArgs _args)
    {
        if (_radioFilterWindow == null)
        {
            _radioFilterWindow = new RadioFilterWindow();
            _radioFilterWindow.OnFilterChanged += () => OnRadioFilterChanged?.Invoke();
        }

        if (_radioFilterWindow.IsOpen)
            _radioFilterWindow.Close();
        else
            _radioFilterWindow.OpenCentered();
    }

    /// <summary>
    /// Sets all visible channel filters to the specified state.
    /// </summary>
    /// <param name="state">The state to set all visible channel filters to (true for enabled, false for disabled).</param>
    /// <remarks>
    /// HardLight: Added "Toggle All" button to channel filter popup
    /// </remarks>
    private void SetAllChannelState(bool state)
    {
        var filtersToUpdate = ChannelFilterOrder
            .Where(_filterStates.ContainsKey)
            .Select(channel => _filterStates[channel])
            .Where(fs => !fs.IsHidden && fs.Pressed != state);
        foreach (var filterState in filtersToUpdate) filterState.Pressed = state;
        OnFilterBulkUpdated?.Invoke();
    }

    /// <summary>
    /// Updates the "All" checkbox lockstep with the culmination of all individual channel checkboxes.
    /// The All checkbox is automatically updated to toggle itself when the rest of the channels are updated to match a new state. Turn on all the channels, and the checkbox toggles itself on.
    /// </summary>
    /// <remarks>
    /// HardLight: Added "Toggle All" button to channel filter popup
    /// </remarks>
    private void UpdateAllChannelCheckboxState()
    {
        var allActive = ChannelFilterOrder
            .All(channel => !_filterStates.TryGetValue(channel, out var filterState) || filterState.IsHidden || filterState.Pressed);

        AllChannelsCheckbox.Pressed = allActive;
    }

    /// <summary>
    /// Event handler for "All" checkbox OnToggled.
    /// Required method to handle events.
    /// </summary>
    /// <param name="args">The event arguments containing the new toggle state.</param>
    /// <remarks>
    /// HardLight: Added "Toggle All" button to channel filter popup
    /// </remarks>
    private void OnAllChannelCheckboxToggled(ButtonToggledEventArgs args) => SetAllChannelState(args.Pressed);

    /// <summary>Returns true if a radio channel should be shown in the chat box.</summary>
    public bool IsRadioChannelVisible(string channelId)
        => _radioFilterWindow?.IsChannelVisible(channelId) ?? true;

    public void UpdateUnread(ChatChannel channel, int? unread)
    {
        if (_filterStates.TryGetValue(channel, out var checkbox))
            checkbox.UpdateUnreadCount(unread);
    }
}
