using Content.Client._NF.Shipyard.BUI;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Actions.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI
{
    [GenerateTypedNameReferences]
    sealed partial class ShipyardRulesPopup : FancyWindow
    {
        private readonly ShipyardConsoleBoundUserInterface _menu;

        public ShipyardRulesPopup(ShipyardConsoleBoundUserInterface owner)
        {
            RobustXamlLoader.Load(this);
            _menu = owner;
            Title = Loc.GetString("shipyard-console-menu-title");
            AcceptButton.OnPressed += OnRulesAccept;
        }

        private void OnRulesAccept(ButtonEventArgs args)
        {
            Close();
        }
    }
}
