name: 'RSI Diff Bot - HardLight'
description: 'Shows modified states in any changed Robust Station Images - Ported from https://github.com/space-wizards/RSIDiffBot'

inputs:
  modified:
    description: 'A list of modified files.'
  removed:
    description: 'A list of removed files.'
  added:
    description: 'A list of changed files.'
  basename:
    description: 'The base repository full name, username/reponame.'
  basesha:
    description: 'The base branch commit hash.'
  headname:
    description: 'The head repository full name, username/reponame.'
  headsha:
    description: 'The head branch commit hash.'
outputs:
  summary-details:
    description: 'A detailed summary of all the states that changed in Markdown.'
    value: ${{ steps.diff.outputs.summary-details }}
  hasDiffs:
    description: '`true` or `false` depending on if there are any RSI changes'
    value: ${{ steps.diff.outputs.hasDiffs }}

runs:
  using: "composite"
  steps:
    - name: Calculate Diff
      id: diff
      env:
         modified: ${{ inputs.modified }}
         removed: ${{ inputs.removed }}
         added: ${{ inputs.added }}
         basename: ${{ inputs.basename }}
         basesha: ${{ inputs.basesha }}
         headname: ${{ inputs.headname }}
         headsha: ${{ inputs.headsha }}
      run: python3 ./.github/actions/rsi-diff/action.py
