using Content.Shared._VRS.Planet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._VRS.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LandgrabUiFragment : BoxContainer
{
    public event Action? OnPurchase;
    public event Action<string>? OnSave;
    public event Action<string>? OnLoad;
    public event Action<string>? OnDelete;
    public event Action? OnAbandon;
    public event Action<string>? OnEngraveDisk;

    public LandgrabUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        PurchaseButton.OnPressed += _ => OnPurchase?.Invoke();
        SaveButton.OnPressed += _ =>
        {
            var slot = SaveSlotEdit.Text.Trim();
            if (!string.IsNullOrEmpty(slot))
                OnSave?.Invoke(slot);
        };
        AbandonButton.OnPressed += _ => OnAbandon?.Invoke();
        EngraveDiskButton.OnPressed += _ => OnEngraveDisk?.Invoke(DiskLabelEdit.Text.Trim());
    }

    public void UpdateState(LandgrabUiState state)
    {
        // Header
        PlanetLabel.Text = state.PlanetName;
        BalanceLabel.Text = Loc.GetString("landgrab-balance", ("amount", state.Balance));

        if (!state.OnValidPlanet)
        {
            LocationLabel.Text = Loc.GetString("landgrab-location-none");
            PlotSizeLabel.Text = string.Empty;
            StatusLabel.Text = Loc.GetString("landgrab-go-to-planet");
            PurchaseButton.Disabled = true;
            SaveButton.Disabled = !state.OwnsPlot;
            AbandonButton.Disabled = !state.OwnsPlot;
        }
        else
        {
            LocationLabel.Text = Loc.GetString(
                "landgrab-location",
                ("x", state.WorldX.ToString("F0")),
                ("y", state.WorldY.ToString("F0"))
            );
            PlotSizeLabel.Text = Loc.GetString("landgrab-plot-size", ("size", state.PlotSize));

            if (state.OwnsPlot)
            {
                StatusLabel.Text = Loc.GetString("landgrab-already-owns");
                PurchaseButton.Disabled = true;
            }
            else if (!state.LocationFree)
            {
                var reasonKey = state.LocationBlockedReason ?? "landgrab-blocked-overlap";
                StatusLabel.Text = Loc.GetString(reasonKey);
                PurchaseButton.Disabled = true;
            }
            else if (state.Balance < state.PurchaseCost)
            {
                StatusLabel.Text = Loc.GetString("landgrab-insufficient-funds");
                PurchaseButton.Disabled = true;
            }
            else
            {
                StatusLabel.Text = Loc.GetString("landgrab-cost", ("cost", state.PurchaseCost));
                PurchaseButton.Disabled = false;
            }

            SaveButton.Disabled = !state.OwnsPlot;
            AbandonButton.Disabled = !state.OwnsPlot;
        }

        // Engrave-disk button: needs to be on a planet AND holding a writable disk.
        EngraveDiskButton.Disabled = !state.OnValidPlanet || !state.HasBlankDisk;
        DiskHintLabel.Text = state.HasBlankDisk
            ? Loc.GetString("landgrab-disk-ready")
            : Loc.GetString("landgrab-disk-missing");

        RebuildSavedList(state);
    }

    private void RebuildSavedList(LandgrabUiState state)
    {
        SavedPlotsContainer.RemoveAllChildren();

        if (state.SavedPlots.Count == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("landgrab-no-saves"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4, 4, 4, 4),
            };
            SavedPlotsContainer.AddChild(empty);
            return;
        }

        foreach (var save in state.SavedPlots)
        {
            var row = new PanelContainer { StyleClasses = { "BackgroundPanel" }, Margin = new Thickness(0, 0, 0, 4) };
            var box = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Margin = new Thickness(6),
                HorizontalExpand = true,
            };
            row.AddChild(box);

            box.AddChild(new Label { Text = save.SlotName, StyleClasses = { "LabelKeyText" } });
            box.AddChild(
                new Label
                {
                    Text = Loc.GetString(
                        "landgrab-save-meta",
                        ("w", save.Width),
                        ("h", save.Height),
                        ("tiles", save.TileCount)
                    ),
                    StyleClasses = { "LabelSubText" },
                }
            );
            box.AddChild(
                new Label
                {
                    Text = Loc.GetString("landgrab-load-cost", ("cost", save.LoadCost)),
                    Margin = new Thickness(0, 2, 0, 4),
                }
            );

            var btnRow = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var loadBtn = new Button
            {
                Text = Loc.GetString("landgrab-load"),
                Disabled =
                    !state.OnValidPlanet || state.OwnsPlot || !state.LocationFree || state.Balance < save.LoadCost,
                HorizontalExpand = true,
                StyleClasses = { "ButtonColorGreen" },
            };
            var capturedSlot = save.SlotName;
            loadBtn.OnPressed += _ => OnLoad?.Invoke(capturedSlot);

            var delBtn = new Button
            {
                Text = Loc.GetString("landgrab-delete"),
                StyleClasses = { "ButtonCaution" },
                Margin = new Thickness(4, 0, 0, 0),
            };
            delBtn.OnPressed += _ => OnDelete?.Invoke(capturedSlot);

            btnRow.AddChild(loadBtn);
            btnRow.AddChild(delBtn);
            box.AddChild(btnRow);

            SavedPlotsContainer.AddChild(row);
        }
    }
}
