- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagRailgun
  result: MagazineRailgun
  completetime: 5
  materials:
    Plasteel: 500
    Gold: 50
    Plasma: 500

- type: latheRecipe
  id: NullEnforcerCableStack
  result: CableNullenforcerStack1
  completetime: 0.1
  materials:
    Steel: 30
    Glass: 30
    Diamond: 30

# Security Borg limbs

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: LeftLegBorgSecurity
  result: LeftLegBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: RightLegBorgSecurity
  result: RightLegBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: HeadBorgSecurity
  result: HeadBorgSecurity

- type: latheRecipe
  parent: BaseBorgLimbRecipe
  id: TorsoBorgSecurity
  result: TorsoBorgSecurity

# Plasma Cutter

- type: latheRecipe
  id: WeaponPlasmaCutter
  result: WeaponPlasmaCutter
  completetime: 5
  materials:
    Steel: 3000
    Plasteel: 3000
    Glass: 500
    Gold: 1000
    Plasma: 1000

# Line Gun

- type: latheRecipe
  id: WeaponLineGunRecipe
  result: WeaponLineGun
  completetime: 7
  materials:
    Steel: 8000
    Plasteel: 8000
    Glass: 3000
    Gold: 2500
    Plasma: 2500
    Diamond: 50