name: "Assign size label"
description: "Assign labels based on pull request change sizes"
inputs:
  sizes:
    description: "Custom size configuration"
    required: false
  pr_no:
    description: 'PR number to run on'
    required: true
  token:
    description: 'Forgejo token to run with'
    required: true
  repo:
    description: 'Repository to run on'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Size Labeler
      env:
        SIZES: ${{ inputs.sizes }}
        FORGEJO_URL: ${{ forgejo.server_url }}
        REPO: ${{ inputs.repo }}
        PR: ${{ inputs.pr_no }}
        TOKEN: ${{ inputs.token }}
      run: python3 ./.github/actions/labeler-size/labeler-size.py
