name: PR Changelogs
# Required Vars:
# Variables:
#   CHANGELOG_DIR - changelog file path, for HL should be `Resources/Changelog/HardlightChangelog.yml`
#   CHANGELOG_EMAIL - Email address to associate with the changelog commits
#   CHANGELOG_USER - User to show as the author of the changelog commits
#   CHANGELOG_MESSAGE - Message to show in the changelog commits
# Secrets:
#   BOT_TOKEN - token for bot that will be uploading the change
#   CHANGELOG_DISCORD_WEBHOOK - Discord webhook for pushing the changelog to
concurrency:
  group: commit_action
  cancel-in-progress: false

on:
  pull_request_target:
    types: [closed]

env:
  FORGEJO_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
  PR_NUMBER: ${{ forgejo.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: forgejo.event.pull_request.merged == true
    steps:
      - name: Checkout Master
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.BOT_TOKEN || secrets.FORGEJO_TOKEN }}
          ref: master

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/changelog"
          npm install
        shell: bash

      - name: Generate Changelog
        id: gen_changelog
        run: |
          cd "Tools/changelog"
          node changelog.js
        shell: bash

      - name: Commit Changelog
        run: |
          git pull origin master
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        continue-on-error: true

      - name: Publish changelog
        run: Tools/actions_changelog_publish_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
          DISCORD_CHANGELOG: ${{ steps.gen_changelog.outputs.changelog }}
        continue-on-error: true
