name: Close PRs on master
on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{forgejo.head_ref == 'master' || forgejo.head_ref == 'main' || forgejo.head_ref == 'develop'}}

    steps:
      - name: Fetch Actions
        # Needed because we aren't checking out the full repo, so just grab the bits we care about
        shell: bash
        run: |
          mkdir actions && cd actions
          git init
          git remote add origin "${{ forgejo.server_url }}/${{ forgejo.repository }}.git"
          git config core.sparseCheckout true
          echo ".github/actions/*" >> .git/info/sparse-checkout
          git fetch --depth=1 --filter=blob:none origin master
          git checkout master
          cd ..
          mv actions/.github .github

      - name: Add Comment
        uses: ./.github/actions/forgejo-pr-comment
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          body: "Thank you for contributing to the Hardlight repository. Unfortunately, it looks like you submitted your pull request from the master branch. We suggest you follow [our git usage documentation](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html) \n\n You can move your current work from the master branch to another branch by doing `git branch <branch_name` and resetting the master branch. \n\n This pr won't be automatically closed. However, a maintainer may close it for this reason."
          action: 'add'
          token: ${{ env.FORGEJO_TOKEN }}
