name: "Labels: PR"

concurrency:
  group: labels
  cancel-in-progress: false

on:
- pull_request_target

jobs:
  labeler:
    if: forgejo.actor != 'HardLight-Auto-Changelog'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Actions
        # Needed because we aren't checking out the full repo, so just grab the bits we care about
        shell: bash
        run: |
          mkdir actions && cd actions
          git init
          git remote add origin "${{ forgejo.server_url }}/${{ forgejo.repository }}.git"
          git config core.sparseCheckout true
          echo ".github/*" >> .git/info/sparse-checkout
          git fetch --depth=1 --filter=blob:none origin master
          git checkout master
          cd ..
          mv actions/.github .github

      - name: Run Labeler
        uses: ./.github/actions/labeler
        with:
          pr_no: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          token: ${{ secrets.BOT_TOKEN || secrets.FORGEJO_TOKEN }}
          repo: ${{ forgejo.event.pull_request.base.repo.full_name || forgejo.repository }}
