name: "Labels: Untriaged"

concurrency:
  group: labels
  cancel-in-progress: false

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Actions
        # Needed because we aren't checking out the full repo, so just grab the bits we care about
        shell: bash
        run: |
          mkdir actions && cd actions
          git init
          git remote add origin "${{ forgejo.server_url }}/${{ forgejo.repository }}.git"
          git config core.sparseCheckout true
          echo ".github/actions/*" >> .git/info/sparse-checkout
          git fetch --depth=1 --filter=blob:none origin master
          git checkout master
          cd ..
          mv actions/.github .github

      - name: Get label count
        id: label_count
        uses: ./.github/actions/forgejo-pr-label
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          action: 'count'
          token: ${{ secrets.BOT_TOKEN || secrets.FORGEJO_TOKEN }}

      - name: Add untriaged label
        if: steps.label_count.outputs.count == '0'
        uses: ./.github/actions/forgejo-pr-label
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          label: 'S: Untriaged'
          action: 'add'
          token: ${{ secrets.BOT_TOKEN || secrets.FORGEJO_TOKEN }}
