name: Map Prototype Checker

on:
  pull_request:
    branches: [ "master" ]
    paths:
    # Entity pathspecs - If any of these change (i.e. suffix changes etc), this check should run.
    - "Resources/Prototypes/Entities/**/*.yml"
    - "Resources/Prototypes/_NF/Entities/**/*.yml"
    - "Resources/Prototypes/Nyanotrasen/Entities/**/*.yml"
    - "Resources/Prototypes/_DV/Entities/**/*.yml"
    # Map pathspecs - If any maps are changed, this should run.
    - "Resources/Maps/**/*.yml"
    # Also the mapchecker itself
    - "Tools/mapchecker/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm

    steps:
    - name: Checkout Master
      uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        apt update
        apt install -y python3-pip
        pip3 install --break-system-packages --ignore-installed -r .github/mapchecker/requirements.txt

    - name: Run mapchecker
      run: |
        python3 ./Tools/mapchecker/mapchecker.py
