name: Diff RSIs

# WIP - This uses a bunch of custom actions that are static for github, need to re-do
on:
  pull_request_target:
    paths:
      - '**.rsi/**.png'

jobs:
  diff:
    name: Diff
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Actions
        # Needed because we aren't checking out the full repo, so just grab the bits we care about
        shell: bash
        run: |
          mkdir actions && cd actions
          git init
          git remote add origin "${{ forgejo.server_url }}/${{ forgejo.repository }}.git"
          git config core.sparseCheckout true
          echo ".github/actions/*" >> .git/info/sparse-checkout
          git fetch --depth=1 --filter=blob:none origin master
          git checkout master
          cd ..
          mv actions/.github .github

      - name: Get changed files
        id: files
        uses: ./.github/actions/forgejo-pr-files
        with:
          format: 'space-delimited'
          pr_no: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          token: ${{ env.FORGEJO_TOKEN }}
          filter: |
            **.rsi
            **.png

      - name: Diff changed RSIs
        id: diff
        uses: ./.github/actions/rsi-diff
        with:
          modified: ${{ steps.files.outputs.modified }}
          removed: ${{ steps.files.outputs.removed }}
          added: ${{ steps.files.outputs.added }}
          basename: ${{ forgejo.event.pull_request.base.repo.full_name }}
          basesha: ${{ forgejo.event.pull_request.base.sha }}
          headname: ${{ forgejo.event.pull_request.head.repo.full_name }}
          headsha: ${{ forgejo.event.pull_request.head.sha }}

      - name: Potentially find comment
        if: steps.diff.outputs.hasDiffs == 'true'
        uses: ./.github/actions/forgejo-pr-comment
        id: fc
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          token: ${{ env.FORGEJO_TOKEN }}
          action: 'search'
          searchBody: 'RSI Diff Bot'

      - name: Create comment if it doesn't exist
        if: steps.fc.outputs.searchID == '' && steps.diff.outputs.hasDiffs == 'true'
        uses: ./.github/actions/forgejo-pr-comment
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          token: ${{ env.FORGEJO_TOKEN }}
          action: 'add'
          body: ${{ steps.diff.outputs.summary-details }}

      - name: Update comment if it exists
        if: steps.fc.outputs.searchID != '' && steps.diff.outputs.hasDiffs == 'true'
        uses: ./.github/actions/forgejo-pr-comment
        with:
          pr: ${{ forgejo.event.issue.number || forgejo.event.pull_request.number }}
          commentID: ${{ steps.fc.outputs.searchID }}
          token: ${{ env.FORGEJO_TOKEN }}
          action: 'update'
          body: |
            ${{ steps.diff.outputs.summary-details }}
            Edit: diff updated after ${{ forgejo.event.pull_request.head.sha }}
