name: Map file schema validator
on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  yaml-schema-validation:
    name: YAML map schema validator
    if: forgejo.event.pull_request.draft == false && forgejo.actor != 'HardLight-Auto-Changelog'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: Pull engine updates
      uses: https://github.com/space-wizards/submodule-dependency@v0.1.5

    - uses: https://github.com/PaulRitter/yaml-schema-validator@v1
      with:
        schema: RobustToolbox/Schemas/mapfile.yml
        path_pattern: .*Resources/Maps/.*
        validators_path: RobustToolbox/Schemas/mapfile_validators.py
        validators_requirements: .github/Schemas/mapfile_requirements.txt
