name: RSI Validator
on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    if: forgejo.event.pull_request.draft == false && forgejo.actor != 'HardLight-Auto-Changelog'
    name: Validate RSIs
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Pull engine updates
        uses: https://github.com/space-wizards/submodule-dependency@v0.1.5

      - name: Set up Python 3.10
        run: |
          apt update
          apt install -y python3-pip

      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --break-system-packages --user pillow jsonschema

      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
